### ISSUE TITLE
The related paper

### ISSUE THREAD

**Issue by FelixDJC** [Alexanderia-Mike/model-fusion-by-graph-matching#1]
Please, what is the paper related to this code?

**Comment by Alexanderia-Mike** [comment]
[[PDF] from mlr.press](https://proceedings.mlr.press/v162/liu22k/liu22k.pdf)
[Deep Neural Network Fusion via Graph Matching with Applications to Model Ensemble and Federated Learning](https://proceedings.mlr.press/v162/liu22k.html)

**Comment by FelixDJC** [comment]
Amazing Work!

**Comment by Alexanderia-Mike** [comment]
Thanks! Actually I believe there is a more complete code repo that belongs to the first author of this paper, and you could contact him about that.
